version: "3.8"

services:
    db:
        image: postgres:14
        container_name: decameron_postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            - laravel
        restart: unless-stopped

    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        user: "www-data"
        container_name: decameron_laravel_app
        networks:
            - laravel
        ports:
            - "8000:80"
        restart: unless-stopped

networks:
    laravel:
        driver: bridge

volumes:
    db-data:
